# Generated by Django 4.0.5 on 2022-08-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeServeur',
            fields=[
                ('code_bar', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='code bar')),
                ('intervenant', models.CharField(blank=True, max_length=50, null=True, verbose_name="L'intervenant")),
                ('fonction_de_intervenant', models.CharField(max_length=50, null=True, verbose_name="fonction d'intervenant")),
                ('Nature_de_la_panne', models.CharField(max_length=100, null=True)),
                ('etat_de_demande', models.CharField(choices=[('Matériel réparé', 'Matériel réparé'), ('Matériel nécessite intervention externe', 'Matériel nécessite intervention externe'), ('Matériel propose à la réforme', 'Matériel propose à la réforme')], default='hors service', max_length=50)),
                ('autres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Serveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.serveur')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeScanner',
            fields=[
                ('code_bar', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='code bar')),
                ('intervenant', models.CharField(max_length=50, null=True, verbose_name="L'intervenant")),
                ('fonction_de_intervenant', models.CharField(max_length=50, null=True, verbose_name="fonction d'intervenant")),
                ('Nature_de_la_panne', models.CharField(max_length=100, null=True)),
                ('etat_de_demande', models.CharField(choices=[('Matériel réparé', 'Matériel réparé'), ('Matériel nécessite intervention externe', 'Matériel nécessite intervention externe'), ('Matériel propose à la réforme', 'Matériel propose à la réforme')], default='hors service', max_length=50)),
                ('autres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.scanner')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeOrdinateur',
            fields=[
                ('code_bar', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='code bar')),
                ('intervenant', models.CharField(max_length=50, null=True, verbose_name="L'intervenant")),
                ('fonction_de_intervenant', models.CharField(max_length=50, null=True, verbose_name="fonction d'intervenant")),
                ('Nature_de_la_panne', models.CharField(max_length=100, null=True)),
                ('etat_de_demande', models.CharField(choices=[('Matériel réparé', 'Matériel réparé'), ('Matériel nécessite intervention externe', 'Matériel nécessite intervention externe'), ('Matériel propose à la réforme', 'Matériel propose à la réforme')], default='hors service', max_length=50)),
                ('autres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ordinateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.ordinateur')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeImprimante',
            fields=[
                ('code_bar', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='code bar')),
                ('intervenant', models.CharField(max_length=50, null=True, verbose_name="L'intervenant")),
                ('fonction_de_intervenant', models.CharField(max_length=50, null=True, verbose_name="fonction d'intervenant")),
                ('Nature_de_la_panne', models.CharField(max_length=100, null=True)),
                ('etat_de_demande', models.CharField(choices=[('Matériel réparé', 'Matériel réparé'), ('Matériel nécessite intervention externe', 'Matériel nécessite intervention externe'), ('Matériel propose à la réforme', 'Matériel propose à la réforme')], default='hors service', max_length=50)),
                ('autres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Imprimante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.imprimante')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEcran',
            fields=[
                ('code_bar', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='code bar')),
                ('intervenant', models.CharField(max_length=50, null=True, verbose_name="L'intervenant")),
                ('fonction_de_intervenant', models.CharField(max_length=50, null=True, verbose_name="fonction d'intervenant")),
                ('Nature_de_la_panne', models.CharField(max_length=100, null=True)),
                ('etat_de_demande', models.CharField(choices=[('Matériel réparé', 'Matériel réparé'), ('Matériel nécessite intervention externe', 'Matériel nécessite intervention externe'), ('Matériel propose à la réforme', 'Matériel propose à la réforme')], default='hors service', max_length=50)),
                ('autres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Ecran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.ecran')),
            ],
        ),
    ]
