# Generated by Django 4.0.5 on 2022-08-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=100, unique=True, verbose_name="numero d'inventaire")),
                ('numero_serie', models.CharField(max_length=100, null=True, unique=True, verbose_name='numero serie')),
                ('marque', models.CharField(max_length=100)),
                ('taille_de_lecran', models.CharField(max_length=100, verbose_name="taille de l'ecran")),
                ('etat_de_materiel', models.CharField(choices=[('Hors service', 'Hors service'), ('Fonctionne', 'Fonctionne'), ('Traitement', 'Traitement')], default='Fonctionne', max_length=100, verbose_name='etat de materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Imprimante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=100, unique=True, verbose_name="numero d'inventaire")),
                ('numero_serie', models.CharField(max_length=100, null=True, unique=True, verbose_name='numero serie')),
                ('marque', models.CharField(max_length=100)),
                ('etat_de_materiel', models.CharField(choices=[('Hors service', 'Hors service'), ('Fonctionne', 'Fonctionne'), ('Traitement', 'Traitement')], default='Fonctionne', max_length=100, verbose_name='etat de materiel')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('resolution', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=100, unique=True, verbose_name="numero d'inventaire")),
                ('numero_serie', models.CharField(max_length=100, null=True, unique=True, verbose_name='numero serie')),
                ('marque', models.CharField(max_length=100, null=True)),
                ('resolution', models.CharField(max_length=100, null=True)),
                ('dimension', models.CharField(max_length=100, null=True)),
                ('etat_de_materiel', models.CharField(choices=[('Hors service', 'Hors service'), ('Fonctionne', 'Fonctionne'), ('Traitement', 'Traitement')], default='Fonctionne', max_length=100, verbose_name='etat de materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=100, unique=True, verbose_name="numero d'inventaire")),
                ('numero_serie', models.CharField(max_length=100, null=True, unique=True, verbose_name='numero serie')),
                ('nom_du_serveur', models.CharField(max_length=100, verbose_name='nom du serveur')),
                ('processeur', models.CharField(max_length=100)),
                ('taille_de_disque_dur', models.CharField(max_length=100, verbose_name='taille de disque dur')),
                ('ram', models.CharField(max_length=100)),
                ('system_d_exploitation', models.CharField(max_length=100, verbose_name="system d'exploitation")),
                ('etat_de_materiel', models.CharField(choices=[('Hors service', 'Hors service'), ('Fonctionne', 'Fonctionne'), ('Traitement', 'Traitement')], default='Fonctionne', max_length=100, verbose_name='etat de materiel')),
                ('Employe_que_gerer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employes.employe')),
            ],
            options={
                'verbose_name': 'Serveur',
            },
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=100, unique=True, verbose_name="numero d'inventaire")),
                ('numero_serie', models.CharField(max_length=100, null=True, unique=True, verbose_name='numero serie')),
                ('marque', models.CharField(max_length=100)),
                ('processeur', models.CharField(max_length=100)),
                ('taille_de_disque_dur', models.CharField(max_length=100, verbose_name='taille de disque dur')),
                ('ram', models.CharField(max_length=100)),
                ('system_d_exploitation', models.CharField(max_length=100, verbose_name="system d'exploitation")),
                ('etat_de_materiel', models.CharField(choices=[('Hors service', 'Hors service'), ('Fonctionne', 'Fonctionne'), ('Traitement', 'Traitement')], default='Fonctionne', max_length=100, verbose_name='etat de materiel')),
                ('Employe_que_gerer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employes.employe')),
                ('ecran', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.ecran')),
                ('imprimante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.imprimante')),
                ('scanner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.scanner')),
            ],
        ),
    ]
